
import DAO.VeiculoDAO;
import beans.Veiculo;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author laboratorio
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cor = new javax.swing.ButtonGroup();
        txt_ano = new javax.swing.JTextField();
        txt_placa = new javax.swing.JTextField();
        rad_preto = new javax.swing.JRadioButton();
        rad_branco = new javax.swing.JRadioButton();
        rad_prata = new javax.swing.JRadioButton();
        rad_vermelho = new javax.swing.JRadioButton();
        rad_azul = new javax.swing.JRadioButton();
        btn_inserir = new javax.swing.JButton();
        lbl_cadastro = new javax.swing.JLabel();
        lbl_marca = new javax.swing.JLabel();
        lbl_modelo = new javax.swing.JLabel();
        lbl_ano = new javax.swing.JLabel();
        lbl_placa = new javax.swing.JLabel();
        lbl_cor = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_cor.add(rad_preto);
        rad_preto.setText("Preto");

        btn_cor.add(rad_branco);
        rad_branco.setText("Branco");

        btn_cor.add(rad_prata);
        rad_prata.setText("Prata");

        btn_cor.add(rad_vermelho);
        rad_vermelho.setText("Vermelho");

        btn_cor.add(rad_azul);
        rad_azul.setText("Azul");

        btn_inserir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_inserir.setText("INSERIR");
        btn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirActionPerformed(evt);
            }
        });

        lbl_cadastro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_cadastro.setText("CADASTRO DE VEICULOS");

        lbl_marca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_marca.setText("MARCA : ");

        lbl_modelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_modelo.setText("MODELO :");

        lbl_ano.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_ano.setText("ANO :");

        lbl_placa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_placa.setText("PLACA :");

        lbl_cor.setText("COR :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_marca, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_modelo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_ano, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_placa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_cor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rad_preto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rad_branco)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rad_prata)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rad_vermelho)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rad_azul))
                        .addComponent(txt_modelo)
                        .addComponent(txt_ano)
                        .addComponent(txt_placa))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_cadastro)
                        .addComponent(txt_marca)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(btn_inserir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cadastro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_marca)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_modelo)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_ano))
                    .addComponent(txt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_placa)
                    .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cor)
                    .addComponent(rad_preto)
                    .addComponent(rad_branco)
                    .addComponent(rad_prata)
                    .addComponent(rad_vermelho)
                    .addComponent(rad_azul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btn_inserir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirActionPerformed
        String marca = txt_marca.getText();
        String modelo = txt_modelo.getText();
        int ano = Integer.parseInt(txt_ano.getText());
        String placa = txt_placa.getText();
        String cor;
        if(rad_preto.isSelected()){
            cor = "preto";
        }else if(rad_branco.isSelected()){
            cor = "branco";
        }else if(rad_prata.isSelected()){
            cor = "prata";
        }else if(rad_vermelho.isSelected()){
            cor = "vermelho";
        }else{
            cor = "azul";
        }

        Veiculo v = new Veiculo();
        v.setMarca(marca);
        v.setModelo(modelo);
        v.setAno(ano);
        v.setPlaca(placa);
        v.setCor(cor);

        VeiculoDAO vDAO = new VeiculoDAO();
        vDAO.inserir(v);

        JOptionPane.showMessageDialog(null, "CADASTRO REALIZADO COM SUCESSO");

        limparFormulario();

    }//GEN-LAST:event_btn_inserirActionPerformed
 private void limparFormulario() {
            txt_marca.setText("");
            txt_modelo.setText("");
            txt_ano.setText("");
            txt_placa.setText("");
            btn_cor.clearSelection();

        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_cor;
    private javax.swing.JButton btn_inserir;
    private javax.swing.JLabel lbl_ano;
    private javax.swing.JLabel lbl_cadastro;
    private javax.swing.JLabel lbl_cor;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_modelo;
    private javax.swing.JLabel lbl_placa;
    private javax.swing.JRadioButton rad_azul;
    private javax.swing.JRadioButton rad_branco;
    private javax.swing.JRadioButton rad_prata;
    private javax.swing.JRadioButton rad_preto;
    private javax.swing.JRadioButton rad_vermelho;
    private javax.swing.JTextField txt_ano;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_placa;
    // End of variables declaration//GEN-END:variables
}
